bind_addr = ":8080"

host_db = "postgres"
port_db = ":5432"
name_db = "texzadanie-db"
user_db = "postgres"
password_db = "PostgresTexzadanie2022"

cache_host = "redis"
cache_password = "RedisTexzadanie2022"
cache_addr = ":6379"
